title: Superkuvar
logo: /assets/img/logo.png
url: https://superkuvar.com
description: Tradicionalna kuhinja i praktični recepti iz bakinih vitrina.
google_analytics: G-KB2P3TFTJ3
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed



